name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Execute Deployment Commands via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            # Check if directory exists, if not clone it
            if [ ! -d "secure-code" ]; then
              git clone https://github.com/code-app-2026/secure-code.git
            fi
            
            # Navigate to the project directory
            cd secure-code/secure-code-server
            
            # Pull the latest code from GitHub
            git pull origin main
            
            # Stop the current running containers safely
            sudo docker-compose down
            
            # Export the WG_HOST automatically so WireGuard knows the server's public IP
            export WG_HOST=${{ secrets.SERVER_IP }}
            export WG_PASSWORD=securecodeadmin
            
            # Rebuild and start the containers in the background
            sudo -E docker-compose up --build -d
